// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)
